Vagrant.configure("2") do |config|
 config.vm.define "ansible-control" do |node|
 node.vm.box = "ubuntu/jammy64"
 node.vm.hostname = "ansible-control"
 node.vm.network "private_network", ip: "192.168.56.10"
 node.vm.provider "virtualbox" do |vb|
 vb.memory = "1024"
 vb.cpus = 1
 vb.name = "ansible-control"
 end
 end
 config.vm.define "web1" do |node|
 node.vm.box = "ubuntu/jammy64"
 node.vm.hostname = "web1"
 node.vm.network "private_network", ip: "192.168.56.11"
 node.vm.provider "virtualbox" do |vb|
 vb.memory = "1024"
 vb.cpus = 1
 vb.name = "web1"
 end
 end
 # Managed Node 2 - Web Server 2 (Ubuntu 22.04)
 config.vm.define "web2" do |node|
 node.vm.box = "ubuntu/jammy64"
 node.vm.hostname = "web2"
 node.vm.network "private_network", ip: "192.168.56.12"
 node.vm.provider "virtualbox" do |vb|
 vb.memory = "1024"
 vb.cpus = 1
 vb.name = "web2"
 end
 end
end