FROM python:3.14.0rc3-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN useradd -m -r appuser && chown -R appuser /app
USER appuser
CMD ["python", "app.py"]