Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.network "private_network", ip: "192.168.56.10"
    config.vm.network "forwarded_port", guest: 5000, host: 5000
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
        vb.name = "devsecops-vm"
    end
    config.ssh.insert_key = false
    config.vm.synced_folder "../app", "/home/vagrant/app"
    config.vm.synced_folder "../.github", "/home/vagrant/pipelines"
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get upgrade -y
        apt-get install -y docker.io git python3 python3-pip curl wget
        usermod -aG docker vagrant
        mkdir -p /etc/docker
        echo '{"insecure-registries": ["localhost:5000", "192.168.56.10:5000", "127.0.0.1:5000"] }' > /etc/docker/daemon.json
        systemctl restart docker
        chmod 666 /var/run/docker.sock
        cp -r /home/vagrant/app /home/vagrant/my-app
        chown -R vagrant:vagrant /home/vagrant/my-app
        chown -R vagrant:vagrant /home/vagrant/pipelines
        docker run -d \
        -p 5000:5000 \
        --restart=always \
        --name registry \
        -v /var/lib/registry:/var/lib/registry \
        registry:2
        echo "✅ Docker Registry запущен на http://192.168.56.10:5000"
        cd /home/vagrant/my-app
        docker build -t 192.168.56.10:5000/my-app:latest .
        docker push 192.168.56.10:5000/my-app:latest
        echo "✅ Образ успешно собран и загружен в реестр: 192.168.56.10:5000/my-app:latest"
        docker images
    SHELL
end
